import express from 'express';
import authenticationToken from '../../middleware/auth/auth.middleware';
import createTag from '../../service/impl/tag/createTag/createTag.impl';
import globalValidator from '../../middleware/globalValidator/globalValidator';
import { validateCreatedTag } from '../../util/validator';
import showTags from '../../service/impl/tag/showTags/showTags.impl';
import showTag from '../../service/impl/tag/showTag/showTag.impl';
const router = express.Router();
router.post('/create-tag', authenticationToken, globalValidator(validateCreatedTag), createTag);
router.get('/show-tags', authenticationToken, showTags);
router.get('/show-tag/:id', authenticationToken, showTag);
export default router;