import express from 'express';
import authenticationToken from '../../middleware/auth/auth.middleware';
import createTag from '../../service/impl/tag/createTag/createTag.impl';
import globalValidator from '../../middleware/globalValidator/globalValidator';
import { validateCreatedTag, validateUpdatedTag } from '../../util/validator';
import showTags from '../../service/impl/tag/showTags/showTags.impl';
import showTag from '../../service/impl/tag/showTag/showTag.impl';
import updateTag from '../../service/impl/tag/updateTag/updateTag.impl';
import deleteTag from '../../service/impl/tag/deleteTag/deleteTag.impl';
const router = express.Router();
router.post('/create-tag', authenticationToken, globalValidator(validateCreatedTag), createTag);
router.get('/show-tags', authenticationToken, showTags);
router.get('/show-tag/:id', authenticationToken, showTag);
router.put('/update-tag/:id', authenticationToken, globalValidator(validateUpdatedTag), updateTag);
router.delete('/delete-tag/:id', authenticationToken, deleteTag);
export default router;