import express from 'express';
import authenticationToken from '../../middleware/auth/auth.middleware';
import globalValidator from '../../middleware/globalValidator/globalValidator';
import { validateUserLoginRegistration, validateUserRegistration } from '../../util/validator';
import register from '../../service/impl/auth/register/register.impl';
import login from '../../service/impl/auth/login/login.impl';
import showUsers from '../../service/impl/auth/showUsers/showUsers.impl';
const router = express.Router();
router.post('create-account', authenticationToken, globalValidator(validateUserRegistration), register);
router.post('/login', authenticationToken, globalValidator(validateUserLoginRegistration), login);
router.get('/show-users', authenticationToken, showUsers);
export default router;
