import express from 'express';
import authenticationToken from '../../middleware/auth/auth.middleware';
import createCategory from '../../service/impl/category/createCategory/createCategory.impl';
import globalValidator from '../../middleware/globalValidator/globalValidator';
import { validateCreatedCategory, validateUpdatedCategory } from '../../util/validator';
import showCategories from '../../service/impl/category/showCategories/showCategories.impl';
import showCategory from '../../service/impl/category/showCategory/showCategory.impl';
import updateCategory from '../../service/impl/category/updateCategory/updateCategory.impl';
const router = express.Router();
router.post('/create-category', authenticationToken, globalValidator(validateCreatedCategory), createCategory);
router.get('/show-categories', authenticationToken, showCategories);
router.get('/show-category/:id', authenticationToken, showCategory);
router.put('/update-category/:id', authenticationToken, globalValidator(validateUpdatedCategory), updateCategory);
export default router;